stages:
    - dockerizeSpring
    - dockerizeReact

dockerizeSpring:
    stage: dockerizeSpring
    script: 
        - "cd ./JavaSpringApp"
        - "mvn clean install"
        # - "docker stop takami"
        # - "docker rm takami"
        - "docker rmi takami"
        - "docker build -t takami ."
        # - "docker restart mysql-takami"
        # - "docker run -p 8080:8080 --name takami --link mysql-takami -d takami"
        # - "docker start takami"
        # - "docker logs takami"
        # - "docker logs mysql-takami"

dockerizeReact:
    stage: dockerizeReact
    script: 
        - "cd ./ReactApp"
        - "docker rmi takamireact"
        - "docker build -t takamireact ."
        
        
