stages:
  - build
  - test

  build:
    stage: build
    script:
      -npm install react-scripts
      -npm install react-bootstrap
      -npm install react-router

test:
  stage: test
  script:
    - npx cypress run

after_script:
    - echo "End CI"
