stages:
  - build
  - test

build:
  stage: build
  script:
   - RUN npm install --silent
-RUN npm install react-scripts
-RUN npm install react-bootstrap
-RUN npm install react-router


test:
  stage: test
  script:
    - npx cypress run

after_script:
    - echo "End CI"
