stages:
    - dockerizeSpring
    - dockerizeReact

dockerizeSpring:
    stage: dockerizeSpring
    script: 
        - "cd ./JavaSpringApp"
        - mvn clean install
        - "docker rmi takami"
        - "docker build -t takami ."
        - "docker restart mysql-takami"
        
